### ISSUE TITLE
Issue starting bot

### ISSUE THREAD

**Issue by Note2Self** [agubelu/discord-music-bot#1]
Experiencing issues when starting bot, 

`TypeError: voice_channel.join is not a function
`  

on this line 

`discord-music-bot\musicbot.js:398
               voice_channel.join().then(connection => {voice_connection = connection;}).catch(console.error);
`

**Comment by Note2Self** [comment]
Some more details on the issue: 

`$ node bot.js
C:\Users\Dean\Documents\tunebot\node_modules\discord-music-bot\musicbot.js:377
                voice_channel.join().then(connection => {voice_connection = conn
ection;}).catch(console.error);
                              ^

TypeError: voice_channel.join is not a function
    at Client.bot.on (C:\Users\Dean\Documents\tunebot\node_modules\discord-music
-bot\musicbot.js:377:17)
    at emitNone (events.js:91:20)
    at Client.emit (events.js:185:7)
    at WebSocketManager._emitReady (C:\Users\Dean\Documents\tunebot\node_modules
\discord.js\src\client\websocket\WebSocketManager.js:325:17)
    at WebSocketManager.checkIfReady (C:\Users\Dean\Documents\tunebot\node_modul
es\discord.js\src\client\websocket\WebSocketManager.js:351:14)
    at GuildCreateHandler.handle (C:\Users\Dean\Documents\tunebot\node_modules\d
iscord.js\src\client\websocket\packets\handlers\GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (C:\Users\Dean\Documents\tunebot\node_modul
es\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:120:65)
    at WebSocketManager.eventMessage (C:\Users\Dean\Documents\tunebot\node_modul
es\discord.js\src\client\websocket\WebSocketManager.js:273:31)
    at WebSocket.onMessage (C:\Users\Dean\Documents\tunebot\node_modules\ws\lib\
WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
`

Am I doing some thing wrong here?

**Comment by agubelu** [comment]
Please check that the voice channel name that you're using in your script matches exactly the name of the voice channel in the server (case sensitive) and, if it's correctly set, that the bot has permission to join it.

**Comment by Note2Self** [comment]
Thank you very much is was the case sensitive issue in the voice channel name. What would be a great feature is to be able search term like this 

!request Maroon 5 

Thank you for your amazing work 💯

**Comment by agubelu** [comment]
Glad to help!

Do you mean searching for a song on YouTube through the bot or just requesting a word instead of a video? If it's the latter, you can `!setalias maroon5 <your video>` and then `!request maroon5`

**Comment by Note2Self** [comment]
An feature by Searching for the YouTube song with a search term through the bot would be a great option. 

Alias is a nice option but you have to set every song. 

And possibility an option to play from Soundcloud would be another awesome feature if you release any future releases

**Comment by agubelu** [comment]
Thanks for your feedback, will look into it.
