### ISSUE TITLE
Issue after recent update

### ISSUE THREAD

**Issue by Note2Self** [agubelu/discord-music-bot#11]
Since the last update with @SavageCore contribution I'm getting errors back from the bot. These are as follows: 

In Discord: 

**The requested video (JGwWNGJdvx8) does not exist or cannot be played.**

This happens when you use the `!search` and `!request` commands. 

The error in cmd line shows this:

`
{ Error: read ECONNRESET
 at exports._errnoException (util.js:1034:11)
  at TLSWrap.onread (net.js:580:26)
code: 'ECONNRESET',
errno: 'ECONNRESET',
 syscall: 'read',
type: 'error',
 target: 
 WebSocket {
domain: null,
 _events: { error: [Function: onerror] },
 _eventsCount: 1,
 _maxListeners: undefined,
_socket: null,
_ultron: null,
_closeReceived: false,
 bytesReceived: 0,
readyState: 3,
supports: { binary: true },
extensions: null,
_binaryType: 'nodebuffer',
 _isServer: false,
  url: 'wss://eu-central369.discord.gg',
protocolVersion: 13,
 _closeTimer: null,
 _closeCode: 1006 } }
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
Error (JGwWNGJdvx8): Error: connect ECONNREFUSED 127.0.0.1:80
`

**Comment by agubelu** [comment]
Are you still having those issues? I can play that video just fine with both the !request and !search commands, and the error seems to come from the Discord server instead of YouTube.

**Comment by SavageCore** [comment]
Strange. It appears to be a connection error with Discord but the specific error is thrown by ytdl.getInfo() failing and I cannot reproduce.

Possibly related to [#108](https://github.com/fent/node-ytdl-core/issues/108) which should have been fixed by [#104](https://github.com/fent/node-ytdl-core/issues/104)

**Comment by Note2Self** [comment]
Hey I seem to have fixed it I just did a `npm install` and it seems to have fixed the issue.

**Comment by SavageCore** [comment]
@Note2Self What was the output? Did ytdl-core update?

**Comment by Note2Self** [comment]
@SavageCore I believe so

**Comment by SavageCore** [comment]
Thanks. So had you installed prior to 31st January originally? If so I think leave this closed as fixed by #104 above.

**Comment by Note2Self** [comment]
I believe so it seems to have fixed the issue :) @SavageCore
