### ISSUE TITLE
Youtube video request issues and audio drops out at certain times.

### ISSUE THREAD

**Issue by onnex** [agubelu/discord-music-bot#2]
The bot works fine for the most part from some videos returned from youtube get a `The requested video could not be found.` in the text channel and some times the audio drops say 2/3 mins in when a requested video plays. 

If you could help with this bug that would be great :)

To add:  Support for search term like !request artist name/title along side the url option and to be able to pull sounds from sound cloud, vimeo and so on would also be a good addition.

**Comment by agubelu** [comment]
Could you please provide an example of a valid video that returns a `The requested video could not be found.` error?

The audio dropping has occurred to me ocasionally and it might be a connection issue or an actual problem with the ytdl-core library that I use to generate audio streams for the bot. I'll get in touch with the dev of said library to try to clarify this particular issue.

The search functionality and support for other platforms such as SoundCloud was mentioned in #1, I'll have a look at them asap :)

**Comment by agubelu** [comment]
Oh, I think you misunderstood. You have to request the video URL or ID, not the video title. Either of these will do:

`!request https://www.youtube.com/watch?v=6_x7gTQOEs4`

or 

`!request 6_x7gTQOEs4`

**Comment by onnex** [comment]
Sorry, I meant to mention when the url is requested. 

 !request https://www.youtube.com/watch?v=6_x7gTQOEs4 I get the message 

 "The requested video could not be found." 

apologies.

**Comment by agubelu** [comment]
Hmm that's weird, it seems to work for me:

![2017-01-26 20_20_04- general - discord](https://cloud.githubusercontent.com/assets/1207202/22346629/0f46faec-e405-11e6-894b-e406b345d639.png)

Where are you hosting your bot? It might be a YT regional restriction or something like that.

**Comment by onnex** [comment]
I'm from the EU could be why but the video plays fine for me. Thank you for helping.
