### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by mirkomilova10** [agubelu/discord-music-bot#2]
So, i've had some problems installing and all but now the bot starts up and accepts songs but it doesn't reproduce them! i wonder if the function addVideoToQueue actually gets the link to the audio file of the youtube video and if savedeo.com works properly :S

**Comment by mirkomilova10** [comment]
im on Debian 7 with noode js v5 and discord.js on the master branch. perhaps it workson the in-dev one?

**Comment by mirkomilova10** [comment]
fixed it, it was a discord.js problem

**Comment by JoeTheDino** [comment]
Hey there, i'm having the same problem, tried to reinstall from scratch, nothing. reinstalling ffmpeg did nothing too. How did you do ? Thanks

**Comment by mirkomilova10** [comment]
1) OS? node.js version? discord.js version? need more info
2) i'd suggest you use my version because this one needs some fixing and i did it for my server: https://github.com/mirkomilova10/discord-music-bot/tree/fixin-issues

**Comment by JoeTheDino** [comment]
Using Ubuntu 14.04, nodejs is v4.2.6, discordjs is v5.3.2.

Thanks, I'm gonna try with your one and tell you

**Comment by mirkomilova10** [comment]
use nodejs 5 and discord.js indev branch

**Comment by mirkomilova10** [comment]
and for ubuntu 14.04 to use ffmpeg use this command
```
sudo add-apt-repository ppa:mc3man/trusty-media && sudo apt-get update && sudo apt-get install ffmpeg
```

**Comment by JoeTheDino** [comment]
i did everything you said and i still have no sound, i don't know what to do since there are no errors

**Comment by mirkomilova10** [comment]
you following these instructions? ```http://discordjs.readthedocs.org/en/latest/installing.html```
If so they are WRONG, don't follow the ```$ apt-get install libav-tools``` command because it causes ffmpeg to fail, only use the command i gave you before

**Comment by JoeTheDino** [comment]
Yes i followed this one, i'm trying to purge this libav-tools and if it's not working, i'll reinstall from a clean install.

**Comment by JoeTheDino** [comment]
Hi there, i reinstalled a

**Comment by mirkomilova10** [comment]
only one to be confirmed to work id ubuntu 14.04, debian is not tested

**Comment by mirkomilova10** [comment]
also, join the [discord api server](https://discord.gg/0SBTUU1wZTUowidM) and ask for more help

**Comment by JoeTheDino** [comment]
Gonna try more on ubuntu. Thank you for everything ^^
