### ISSUE TITLE
bot.voiceConnection.playFile

### ISSUE THREAD

**Issue by Adrion** [agubelu/discord-music-bot#4]
`bot.voiceConnection.playFile(queue[0]['url']); `
bot-commons.js::501

playFile makes the bot crash... 
the url is working but not the discord module. Did you add this issue ?

**Comment by mirkomilova10** [comment]
hi, i made a fork of the project to improve it and fix some issues: https://github.com/mirkomilova10/discord-music-bot/tree/fixin-issues

**Comment by Adrion** [comment]
great fork thanks ;)
